In [1]:
import pandas as pd
import numpy as np

C:\Users\vkhosla\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\vkhosla\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [87]:
lst  = [0,1,2,3,4,5,6,7,8]
l1 =np.array(lst).reshape(3,3)
print (l1)
result = {'mean': [np.sum(l1,axis=0),np.sum(l1,axis=1),np.sum(l1)],
         'variance':[np.var(l1,axis=0),np.var(l1,axis=1),np.var(l1)],
         'standard deviation':[np.std(l1,axis=0),np.std(l1,axis=1),np.std(l1)],
         'max':[np.max(l1,axis=0),np.max(l1,axis=1),np.max(l1)],
         'min':[np.min(l1,axis=0),np.min(l1,axis=1),np.min(l1)]}
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
{'mean': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36], 'variance': [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667], 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611], 'max': [array([6, 7, 8]), array([2, 5, 8]), 8], 'min': [array([0, 1, 2]), array([0, 3, 6]), 0]}


In [2]:
df=pd.read_csv(r'downloads\adult_data.csv')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [32]:
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [70]:
race_count =df['race'].value_counts()
print (race_count)

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64


In [11]:
aa = df[df['sex']=='Male']['age'].mean()
print (aa)

39.43354749885268


In [73]:
bb = round(len(df[df['education']=='Bachelors'])*100/len(df),1)
bb

16.4

In [70]:
#What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?
len(df[(~df['education'].isin(['Bachelors','Masters','Doctorate'])) & (df['salary'] == '>50K')])/len(df[~df['education'].isin(['Bachelors','Masters','Doctorate'])])


0.173713601914639

In [10]:
df =pd.read_parquet(r'downloads\xme_oob (1).parquet', engine='fastparquet')

In [42]:
len(df[(df['hours-per-week']==1) & (df['salary']== '>50K')])/len(df[df['hours-per-week']==1])

0.1

In [41]:
len(df[df['hours-per-week']==1])

20

In [62]:
df[df['salary']== '>50K']['native-country'].groupby(df['native-country']).count()

native-country
?                      146
Cambodia                 7
Canada                  39
China                   20
Columbia                 2
Cuba                    25
Dominican-Republic       2
Ecuador                  4
El-Salvador              9
England                 30
France                  12
Germany                 44
Greece                   8
Guatemala                3
Haiti                    4
Honduras                 1
Hong                     6
Hungary                  3
India                   40
Iran                    18
Ireland                  5
Italy                   25
Jamaica                 10
Japan                   24
Laos                     2
Mexico                  33
Nicaragua                2
Peru                     2
Philippines             61
Poland                  12
Portugal                 4
Puerto-Rico             12
Scotland                 3
South                   16
Taiwan                  20
Thailand                 3
Trinadad&Toba

In [66]:
df[(df['salary']=='>50K') & (df['native-country']=='India')]['occupation'].value_counts().idxmax()

'Prof-specialty'